"""
gen_testbench.py
================
Generate a SystemVerilog testbench for the Hopfield LUT FSM wrapper.

The testbench mirrors the Python fixed-point and noisy-recall tests exactly:
  1. Fixed-point test: each stored pattern is loaded as initial state;
     the FSM runs until convergence; the output must equal the pattern.
  2. Noisy recall: η fraction of bits are flipped; the FSM runs; output
     must match the original pattern (correct basin-of-attraction recall).

Patterns are re-generated from the training seed so they are identical to
those used during training.

Usage
-----
    python phase2/gen_testbench.py \\
      --meta  phase1/results/truth_tables/pseudo_s0p00/pipeline_meta.json \\
      --out   phase2/tb/hopfield_tb.sv \\
      --module hopfield_lut \\
      --noise 0.0 0.15 0.30 \\
      --noise-trials 20 \\
      --seed 42

    # Then simulate with iverilog:
    iverilog -g2012 -o sim.out \\
        phase2/tb/hopfield_tb.sv \\
        phase2/rtl/pseudo_dense.sv
    vvp sim.out
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


# ─────────────────────────────────────────────────────────────────────────────
# Pattern helpers
# ─────────────────────────────────────────────────────────────────────────────

def bipolar_to_bin(pattern: np.ndarray) -> int:
    """Convert ±1 pattern to integer with LSB = pattern[0]."""
    bits = ((pattern + 1) // 2).astype(int)   # +1→1, -1→0
    val = 0
    for i, b in enumerate(bits):
        val |= (int(b) << i)
    return val


def bin_to_sv_literal(val: int, N: int) -> str:
    """Format integer as SV binary literal, e.g. 16'b0101_1100_..."""
    bits = format(val, f'0{N}b')
    # insert underscore every 4 bits for readability
    groups = [bits[max(0, i-4):i] for i in range(len(bits), 0, -4)][::-1]
    return f"{N}'b{'_'.join(groups)}"


def make_noisy(pattern: np.ndarray, noise_frac: float, rng: np.random.Generator) -> np.ndarray:
    N = len(pattern)
    n_flip = max(0, round(noise_frac * N))
    noisy = pattern.copy()
    if n_flip > 0:
        noisy[rng.choice(N, size=n_flip, replace=False)] *= -1.0
    return noisy


# ─────────────────────────────────────────────────────────────────────────────
# Testbench generator
# ─────────────────────────────────────────────────────────────────────────────

def generate_testbench(
    N: int,
    M: int,
    seed: int,
    noise_fracs: list[float],
    n_noise_trials: int,
    module_name: str,
    top_name: str,
    tb_label: str,
) -> str:
    """
    Return the full SystemVerilog testbench as a string.

    The testbench is self-contained: patterns are hardcoded from the training
    seed so it matches the Python simulation exactly.
    """
    rng_train = np.random.default_rng(seed)
    patterns = rng_train.choice([-1.0, 1.0], size=(M, N))

    rng_noise = np.random.default_rng(seed + 1000)

    # ── Build test vectors ──────────────────────────────────────────────────
    tests = []  # list of (init_val, expected_val, description)

    # Fixed-point tests
    for p_idx in range(M):
        pat = patterns[p_idx]
        val = bipolar_to_bin(pat)
        tests.append((val, val, f"fp[{p_idx}]"))

    # Noisy recall tests
    for p_idx in range(M):
        pat = patterns[p_idx]
        expected_val = bipolar_to_bin(pat)
        for eta in noise_fracs:
            if eta == 0.0:
                continue
            for trial in range(n_noise_trials):
                noisy = make_noisy(pat, eta, rng_noise)
                init_val = bipolar_to_bin(noisy)
                pct = int(eta * 100)
                desc = f"recall_p{p_idx}_eta{pct:02d}_t{trial}"
                tests.append((init_val, expected_val, desc))

    n_tests = len(tests)
    max_sweeps = 4 * N  # generous timeout: 4 full cyclic sweeps

    # ── Emit SV ─────────────────────────────────────────────────────────────
    lines = []
    lines += [
        f"// Auto-generated by gen_testbench.py",
        f"// Testbench for {top_name} (wraps {module_name})",
        f"// N={N}  M={M}  seed={seed}  label={tb_label}",
        f"// Tests: {M} fixed-point + {n_tests - M} noisy recall",
        f"",
        f"`timescale 1ns/1ps",
        f"",
        f"module hopfield_tb;",
        f"",
        f"    // ─── Parameters ───────────────────────────────────────────",
        f"    localparam int N          = {N};",
        f"    localparam int M          = {M};",
        f"    localparam int N_TESTS    = {n_tests};",
        f"    localparam int MAX_CYCLES = {max_sweeps * N};  // {max_sweeps} full sweeps",
        f"",
        f"    // ─── DUT signals ──────────────────────────────────────────",
        f"    logic             clk, rst_n, load;",
        f"    logic [N-1:0]     i_state, o_state;",
        f"    logic             o_done;",
        f"",
        f"    // ─── DUT instantiation ────────────────────────────────────",
        f"    {top_name} #(.N(N)) dut (",
        f"        .clk     (clk),",
        f"        .rst_n   (rst_n),",
        f"        .load    (load),",
        f"        .i_state (i_state),",
        f"        .o_state (o_state),",
        f"        .o_done  (o_done)",
        f"    );",
        f"",
        f"    // ─── Clock (10 ns period) ─────────────────────────────────",
        f"    initial clk = 0;",
        f"    always #5 clk = ~clk;",
        f"",
        f"    // ─── Stored patterns (from Python, seed={seed}) ──────────",
    ]

    # Emit pattern localparams
    for p_idx, pat in enumerate(patterns):
        sv_lit = bin_to_sv_literal(bipolar_to_bin(pat), N)
        lines.append(f"    localparam logic [N-1:0] PAT_{p_idx} = {sv_lit};  // {format(bipolar_to_bin(pat), f'0{N}b')}")

    lines += [
        f"",
        f"    // ─── Test vectors ─────────────────────────────────────────",
        f"    // {{init_state, expected_state}}",
        f"    logic [N-1:0] tv_init     [0:N_TESTS-1];",
        f"    logic [N-1:0] tv_expected [0:N_TESTS-1];",
        f"    string        tv_name     [0:N_TESTS-1];",
        f"",
        f"    // ─── Counters ─────────────────────────────────────────────",
        f"    int pass_cnt, fail_cnt, timeout_cnt;",
        f"",
        f"    // ─── Run-one-test task ────────────────────────────────────",
        f"    task automatic run_one_test(input int t_idx);",
        f"        int cyc;",
        f"        logic [N-1:0] init_s, exp_s;",
        f"        init_s = tv_init[t_idx];",
        f"        exp_s  = tv_expected[t_idx];",
        f"",
        f"        // Load phase",
        f"        @(posedge clk); #1;",
        f"        load = 1'b1;",
        f"        i_state = init_s;",
        f"        @(posedge clk); #1;",
        f"        load = 1'b0;",
        f"",
        f"        // Wait for convergence or timeout",
        f"        cyc = 0;",
        f"        while (!o_done && cyc < MAX_CYCLES) begin",
        f"            @(posedge clk); #1;",
        f"            cyc = cyc + 1;",
        f"        end",
        f"",
        f"        // Evaluate",
        f"        if (!o_done) begin",
        f"            $display(\"TIMEOUT [%0d] %s  init=%b\", t_idx, tv_name[t_idx], init_s);",
        f"            timeout_cnt = timeout_cnt + 1;",
        f"            fail_cnt    = fail_cnt    + 1;",
        f"        end else if (o_state === exp_s) begin",
        f"            $display(\"PASS    [%0d] %s\", t_idx, tv_name[t_idx]);",
        f"            pass_cnt = pass_cnt + 1;",
        f"        end else begin",
        f"            $display(\"FAIL    [%0d] %s  expected=%b  got=%b\",",
        f"                     t_idx, tv_name[t_idx], exp_s, o_state);",
        f"            fail_cnt = fail_cnt + 1;",
        f"        end",
        f"    endtask",
        f"",
        f"    // ─── Main stimulus ────────────────────────────────────────",
        f"    initial begin",
        f"        // Init",
        f"        rst_n = 1'b0; load = 1'b0; i_state = '0;",
        f"        pass_cnt = 0; fail_cnt = 0; timeout_cnt = 0;",
        f"        repeat(4) @(posedge clk);",
        f"        rst_n = 1'b1;",
        f"        @(posedge clk);",
        f"",
        f"        // ── Populate test vectors ──────────────────────────",
    ]

    # Emit test vector assignments
    for t_idx, (init_v, exp_v, desc) in enumerate(tests):
        init_lit = bin_to_sv_literal(init_v, N)
        exp_lit  = bin_to_sv_literal(exp_v,  N)
        lines.append(f'        tv_init[{t_idx:3d}] = {init_lit};  tv_expected[{t_idx:3d}] = {exp_lit};  tv_name[{t_idx:3d}] = "{desc}";')

    lines += [
        f"",
        f"        // ── Run all tests ─────────────────────────────────",
        f"        $display(\"\");",
        f"        $display(\"=== Hopfield SV testbench: {tb_label} (N={N}, M={M}) ===\");",
        f"        $display(\"\");",
        f"",
        f"        $display(\"--- Fixed-point tests (%0d patterns) ---\", M);",
        f"        for (int t = 0; t < M; t++)",
        f"            run_one_test(t);",
        f"",
    ]

    if n_tests > M:
        lines += [
            f"        $display(\"\");",
            f"        $display(\"--- Noisy recall tests (%0d vectors) ---\", N_TESTS - M);",
            f"        for (int t = M; t < N_TESTS; t++)",
            f"            run_one_test(t);",
            f"",
        ]

    lines += [
        f"        // ── Summary ───────────────────────────────────────",
        f"        $display(\"\");",
        f"        $display(\"=== SUMMARY: %0d / %0d passed  (%0d timeouts) ===\",",
        f"                 pass_cnt, N_TESTS, timeout_cnt);",
        f"        if (fail_cnt == 0)",
        f"            $display(\"ALL TESTS PASSED\");",
        f"        else",
        f"            $display(\"%0d FAILURES\", fail_cnt);",
        f"        $display(\"\");",
        f"        $finish;",
        f"    end",
        f"",
        f"endmodule  // hopfield_tb",
        f"",
    ]

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate a SystemVerilog testbench for the Hopfield LUT FSM."
    )
    parser.add_argument("--meta",    type=str, required=True,
                        help="Path to pipeline_meta.json from hnn_to_truth_table.py")
    parser.add_argument("--out",     type=str, required=True,
                        help="Output .sv testbench path")
    parser.add_argument("--module",  type=str, default="hopfield_lut",
                        help="Name of the combinational LUT module")
    parser.add_argument("--top",     type=str, default=None,
                        help="Name of the FSM top module (default: <module>_top→hopfield_top)")
    parser.add_argument("--noise",   nargs="+", type=float, default=[0.0, 0.15, 0.30],
                        help="Noise fractions to test (η values)")
    parser.add_argument("--noise-trials", type=int, default=20,
                        help="Noisy probes per pattern per noise level")
    parser.add_argument("--seed",    type=int, default=None,
                        help="Override RNG seed (default: from meta JSON)")
    args = parser.parse_args()

    with open(args.meta) as f:
        meta = json.load(f)

    N    = meta["N"]
    M    = meta["M"]
    seed = args.seed if args.seed is not None else meta["seed"]
    rule = meta.get("rule", "unknown")

    top_name = args.top or args.module.replace("_lut", "_top")
    if "_lut" not in args.module:
        top_name = args.top or (args.module + "_top")

    tb_label = f"{rule}_N{N}_M{M}_seed{seed}"

    sv = generate_testbench(
        N=N,
        M=M,
        seed=seed,
        noise_fracs=args.noise,
        n_noise_trials=args.noise_trials,
        module_name=args.module,
        top_name=top_name,
        tb_label=tb_label,
    )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sv)

    n_fp    = M
    n_noise = sum(1 for eta in args.noise if eta > 0) * M * args.noise_trials
    print(f"Generated testbench → {out}")
    print(f"  N={N}, M={M}, seed={seed}, rule={rule}")
    print(f"  {n_fp} fixed-point tests + {n_noise} noisy recall tests = {n_fp + n_noise} total")
    print(f"  Noise levels: {args.noise}  ({args.noise_trials} trials each)")
    print(f"  DUT: {top_name} #(.N({N}))")
    print(f"")
    print(f"Simulate with:")
    print(f"  iverilog -g2012 -o sim.out {out} <rtl_file.sv>")
    print(f"  vvp sim.out")
