// Auto-generated by gen_testbench.py
// Testbench for hopfield_top (wraps hopfield_lut)
// N=16  M=4  seed=42  label=pseudoinverse_N16_M4_seed42
// Tests: 4 fixed-point + 160 noisy recall

`timescale 1ns/1ps

module hopfield_tb;

    // ─── Parameters ───────────────────────────────────────────
    localparam int N          = 16;
    localparam int M          = 4;
    localparam int N_TESTS    = 164;
    localparam int MAX_CYCLES = 1024;  // 64 full sweeps

    // ─── DUT signals ──────────────────────────────────────────
    logic             clk, rst_n, load;
    logic [N-1:0]     i_state, o_state;
    logic             o_done;

    // ─── DUT instantiation ────────────────────────────────────
    hopfield_top #(.N(N)) dut (
        .clk     (clk),
        .rst_n   (rst_n),
        .load    (load),
        .i_state (i_state),
        .o_state (o_state),
        .o_done  (o_done)
    );

    // ─── Clock (10 ns period) ─────────────────────────────────
    initial clk = 0;
    always #5 clk = ~clk;

    // ─── Stored patterns (from Python, seed=42) ──────────
    localparam logic [N-1:0] PAT_0 = 16'b1111_1100_1010_0110;  // 1111110010100110
    localparam logic [N-1:0] PAT_1 = 16'b0001_1011_1001_0101;  // 0001101110010101
    localparam logic [N-1:0] PAT_2 = 16'b1010_0110_1011_0110;  // 1010011010110110
    localparam logic [N-1:0] PAT_3 = 16'b1011_1101_0000_0111;  // 1011110100000111

    // ─── Test vectors ─────────────────────────────────────────
    // {init_state, expected_state}
    logic [N-1:0] tv_init     [0:N_TESTS-1];
    logic [N-1:0] tv_expected [0:N_TESTS-1];
    string        tv_name     [0:N_TESTS-1];

    // ─── Counters ─────────────────────────────────────────────
    int pass_cnt, fail_cnt, timeout_cnt;

    // ─── Run-one-test task ────────────────────────────────────
    task automatic run_one_test(input int t_idx);
        int cyc;
        logic [N-1:0] init_s, exp_s;
        init_s = tv_init[t_idx];
        exp_s  = tv_expected[t_idx];

        // Load phase
        @(posedge clk); #1;
        load = 1'b1;
        i_state = init_s;
        @(posedge clk); #1;
        load = 1'b0;

        // Wait for convergence or timeout
        cyc = 0;
        while (!o_done && cyc < MAX_CYCLES) begin
            @(posedge clk); #1;
            cyc = cyc + 1;
        end

        // Evaluate
        if (!o_done) begin
            $display("TIMEOUT [%0d] %s  init=%b", t_idx, tv_name[t_idx], init_s);
            timeout_cnt = timeout_cnt + 1;
            fail_cnt    = fail_cnt    + 1;
        end else if (o_state === exp_s) begin
            $display("PASS    [%0d] %s", t_idx, tv_name[t_idx]);
            pass_cnt = pass_cnt + 1;
        end else begin
            $display("FAIL    [%0d] %s  expected=%b  got=%b",
                     t_idx, tv_name[t_idx], exp_s, o_state);
            fail_cnt = fail_cnt + 1;
        end
    endtask

    // ─── Main stimulus ────────────────────────────────────────
    initial begin
        // Init
        rst_n = 1'b0; load = 1'b0; i_state = '0;
        pass_cnt = 0; fail_cnt = 0; timeout_cnt = 0;
        repeat(4) @(posedge clk);
        rst_n = 1'b1;
        @(posedge clk);

        // ── Populate test vectors ──────────────────────────
        tv_init[  0] = 16'b1111_1100_1010_0110;  tv_expected[  0] = 16'b1111_1100_1010_0110;  tv_name[  0] = "fp[0]";
        tv_init[  1] = 16'b0001_1011_1001_0101;  tv_expected[  1] = 16'b0001_1011_1001_0101;  tv_name[  1] = "fp[1]";
        tv_init[  2] = 16'b1010_0110_1011_0110;  tv_expected[  2] = 16'b1010_0110_1011_0110;  tv_name[  2] = "fp[2]";
        tv_init[  3] = 16'b1011_1101_0000_0111;  tv_expected[  3] = 16'b1011_1101_0000_0111;  tv_name[  3] = "fp[3]";
        tv_init[  4] = 16'b1111_0100_1000_0110;  tv_expected[  4] = 16'b1111_1100_1010_0110;  tv_name[  4] = "recall_p0_eta15_t0";
        tv_init[  5] = 16'b1111_1100_1000_0010;  tv_expected[  5] = 16'b1111_1100_1010_0110;  tv_name[  5] = "recall_p0_eta15_t1";
        tv_init[  6] = 16'b1111_0100_1110_0110;  tv_expected[  6] = 16'b1111_1100_1010_0110;  tv_name[  6] = "recall_p0_eta15_t2";
        tv_init[  7] = 16'b1111_1100_0010_0010;  tv_expected[  7] = 16'b1111_1100_1010_0110;  tv_name[  7] = "recall_p0_eta15_t3";
        tv_init[  8] = 16'b1111_1101_1010_0010;  tv_expected[  8] = 16'b1111_1100_1010_0110;  tv_name[  8] = "recall_p0_eta15_t4";
        tv_init[  9] = 16'b1111_0110_1010_0110;  tv_expected[  9] = 16'b1111_1100_1010_0110;  tv_name[  9] = "recall_p0_eta15_t5";
        tv_init[ 10] = 16'b1111_1000_1010_0111;  tv_expected[ 10] = 16'b1111_1100_1010_0110;  tv_name[ 10] = "recall_p0_eta15_t6";
        tv_init[ 11] = 16'b1111_1101_1010_1110;  tv_expected[ 11] = 16'b1111_1100_1010_0110;  tv_name[ 11] = "recall_p0_eta15_t7";
        tv_init[ 12] = 16'b1011_1100_1010_0100;  tv_expected[ 12] = 16'b1111_1100_1010_0110;  tv_name[ 12] = "recall_p0_eta15_t8";
        tv_init[ 13] = 16'b1110_1100_1010_0100;  tv_expected[ 13] = 16'b1111_1100_1010_0110;  tv_name[ 13] = "recall_p0_eta15_t9";
        tv_init[ 14] = 16'b1101_1100_1010_0111;  tv_expected[ 14] = 16'b1111_1100_1010_0110;  tv_name[ 14] = "recall_p0_eta15_t10";
        tv_init[ 15] = 16'b1011_1110_1010_0110;  tv_expected[ 15] = 16'b1111_1100_1010_0110;  tv_name[ 15] = "recall_p0_eta15_t11";
        tv_init[ 16] = 16'b1111_1100_0000_0110;  tv_expected[ 16] = 16'b1111_1100_1010_0110;  tv_name[ 16] = "recall_p0_eta15_t12";
        tv_init[ 17] = 16'b1111_1101_1010_0111;  tv_expected[ 17] = 16'b1111_1100_1010_0110;  tv_name[ 17] = "recall_p0_eta15_t13";
        tv_init[ 18] = 16'b1111_1100_1010_1010;  tv_expected[ 18] = 16'b1111_1100_1010_0110;  tv_name[ 18] = "recall_p0_eta15_t14";
        tv_init[ 19] = 16'b1111_1000_1010_0010;  tv_expected[ 19] = 16'b1111_1100_1010_0110;  tv_name[ 19] = "recall_p0_eta15_t15";
        tv_init[ 20] = 16'b1111_1100_0010_0100;  tv_expected[ 20] = 16'b1111_1100_1010_0110;  tv_name[ 20] = "recall_p0_eta15_t16";
        tv_init[ 21] = 16'b1111_0000_1010_0110;  tv_expected[ 21] = 16'b1111_1100_1010_0110;  tv_name[ 21] = "recall_p0_eta15_t17";
        tv_init[ 22] = 16'b1110_1100_1000_0110;  tv_expected[ 22] = 16'b1111_1100_1010_0110;  tv_name[ 22] = "recall_p0_eta15_t18";
        tv_init[ 23] = 16'b1101_1100_1011_0110;  tv_expected[ 23] = 16'b1111_1100_1010_0110;  tv_name[ 23] = "recall_p0_eta15_t19";
        tv_init[ 24] = 16'b1111_1110_0110_1111;  tv_expected[ 24] = 16'b1111_1100_1010_0110;  tv_name[ 24] = "recall_p0_eta30_t0";
        tv_init[ 25] = 16'b1010_0101_1110_0110;  tv_expected[ 25] = 16'b1111_1100_1010_0110;  tv_name[ 25] = "recall_p0_eta30_t1";
        tv_init[ 26] = 16'b1011_1101_1000_1010;  tv_expected[ 26] = 16'b1111_1100_1010_0110;  tv_name[ 26] = "recall_p0_eta30_t2";
        tv_init[ 27] = 16'b1011_0001_1011_0110;  tv_expected[ 27] = 16'b1111_1100_1010_0110;  tv_name[ 27] = "recall_p0_eta30_t3";
        tv_init[ 28] = 16'b1101_1000_1000_1111;  tv_expected[ 28] = 16'b1111_1100_1010_0110;  tv_name[ 28] = "recall_p0_eta30_t4";
        tv_init[ 29] = 16'b0111_1000_1110_1100;  tv_expected[ 29] = 16'b1111_1100_1010_0110;  tv_name[ 29] = "recall_p0_eta30_t5";
        tv_init[ 30] = 16'b1100_1101_1010_0011;  tv_expected[ 30] = 16'b1111_1100_1010_0110;  tv_name[ 30] = "recall_p0_eta30_t6";
        tv_init[ 31] = 16'b0111_1100_1100_0011;  tv_expected[ 31] = 16'b1111_1100_1010_0110;  tv_name[ 31] = "recall_p0_eta30_t7";
        tv_init[ 32] = 16'b1001_1000_1000_0111;  tv_expected[ 32] = 16'b1111_1100_1010_0110;  tv_name[ 32] = "recall_p0_eta30_t8";
        tv_init[ 33] = 16'b1101_1100_0001_0111;  tv_expected[ 33] = 16'b1111_1100_1010_0110;  tv_name[ 33] = "recall_p0_eta30_t9";
        tv_init[ 34] = 16'b1011_1001_0010_0010;  tv_expected[ 34] = 16'b1111_1100_1010_0110;  tv_name[ 34] = "recall_p0_eta30_t10";
        tv_init[ 35] = 16'b1100_1000_1010_1100;  tv_expected[ 35] = 16'b1111_1100_1010_0110;  tv_name[ 35] = "recall_p0_eta30_t11";
        tv_init[ 36] = 16'b0010_1100_1110_0100;  tv_expected[ 36] = 16'b1111_1100_1010_0110;  tv_name[ 36] = "recall_p0_eta30_t12";
        tv_init[ 37] = 16'b0111_1001_1111_0110;  tv_expected[ 37] = 16'b1111_1100_1010_0110;  tv_name[ 37] = "recall_p0_eta30_t13";
        tv_init[ 38] = 16'b1111_0111_1110_1110;  tv_expected[ 38] = 16'b1111_1100_1010_0110;  tv_name[ 38] = "recall_p0_eta30_t14";
        tv_init[ 39] = 16'b1011_0111_1010_0010;  tv_expected[ 39] = 16'b1111_1100_1010_0110;  tv_name[ 39] = "recall_p0_eta30_t15";
        tv_init[ 40] = 16'b1111_0101_0011_0111;  tv_expected[ 40] = 16'b1111_1100_1010_0110;  tv_name[ 40] = "recall_p0_eta30_t16";
        tv_init[ 41] = 16'b1101_1101_0010_0011;  tv_expected[ 41] = 16'b1111_1100_1010_0110;  tv_name[ 41] = "recall_p0_eta30_t17";
        tv_init[ 42] = 16'b0101_1000_1011_0111;  tv_expected[ 42] = 16'b1111_1100_1010_0110;  tv_name[ 42] = "recall_p0_eta30_t18";
        tv_init[ 43] = 16'b0111_0100_0110_0111;  tv_expected[ 43] = 16'b1111_1100_1010_0110;  tv_name[ 43] = "recall_p0_eta30_t19";
        tv_init[ 44] = 16'b0001_1011_0011_0101;  tv_expected[ 44] = 16'b0001_1011_1001_0101;  tv_name[ 44] = "recall_p1_eta15_t0";
        tv_init[ 45] = 16'b0001_1010_1001_0100;  tv_expected[ 45] = 16'b0001_1011_1001_0101;  tv_name[ 45] = "recall_p1_eta15_t1";
        tv_init[ 46] = 16'b0011_1011_1001_0111;  tv_expected[ 46] = 16'b0001_1011_1001_0101;  tv_name[ 46] = "recall_p1_eta15_t2";
        tv_init[ 47] = 16'b0001_1111_1000_0101;  tv_expected[ 47] = 16'b0001_1011_1001_0101;  tv_name[ 47] = "recall_p1_eta15_t3";
        tv_init[ 48] = 16'b1001_1001_1001_0101;  tv_expected[ 48] = 16'b0001_1011_1001_0101;  tv_name[ 48] = "recall_p1_eta15_t4";
        tv_init[ 49] = 16'b0001_1011_1011_0100;  tv_expected[ 49] = 16'b0001_1011_1001_0101;  tv_name[ 49] = "recall_p1_eta15_t5";
        tv_init[ 50] = 16'b0011_1011_1001_0100;  tv_expected[ 50] = 16'b0001_1011_1001_0101;  tv_name[ 50] = "recall_p1_eta15_t6";
        tv_init[ 51] = 16'b0100_1011_1001_0101;  tv_expected[ 51] = 16'b0001_1011_1001_0101;  tv_name[ 51] = "recall_p1_eta15_t7";
        tv_init[ 52] = 16'b1001_0011_1001_0101;  tv_expected[ 52] = 16'b0001_1011_1001_0101;  tv_name[ 52] = "recall_p1_eta15_t8";
        tv_init[ 53] = 16'b0101_1011_1101_0101;  tv_expected[ 53] = 16'b0001_1011_1001_0101;  tv_name[ 53] = "recall_p1_eta15_t9";
        tv_init[ 54] = 16'b0101_1011_1101_0101;  tv_expected[ 54] = 16'b0001_1011_1001_0101;  tv_name[ 54] = "recall_p1_eta15_t10";
        tv_init[ 55] = 16'b0001_1111_1001_1101;  tv_expected[ 55] = 16'b0001_1011_1001_0101;  tv_name[ 55] = "recall_p1_eta15_t11";
        tv_init[ 56] = 16'b0010_1011_1001_0101;  tv_expected[ 56] = 16'b0001_1011_1001_0101;  tv_name[ 56] = "recall_p1_eta15_t12";
        tv_init[ 57] = 16'b0001_1111_1101_0101;  tv_expected[ 57] = 16'b0001_1011_1001_0101;  tv_name[ 57] = "recall_p1_eta15_t13";
        tv_init[ 58] = 16'b0000_1011_1001_1101;  tv_expected[ 58] = 16'b0001_1011_1001_0101;  tv_name[ 58] = "recall_p1_eta15_t14";
        tv_init[ 59] = 16'b0001_1011_1001_1100;  tv_expected[ 59] = 16'b0001_1011_1001_0101;  tv_name[ 59] = "recall_p1_eta15_t15";
        tv_init[ 60] = 16'b0011_1010_1001_0101;  tv_expected[ 60] = 16'b0001_1011_1001_0101;  tv_name[ 60] = "recall_p1_eta15_t16";
        tv_init[ 61] = 16'b0000_1011_1001_0111;  tv_expected[ 61] = 16'b0001_1011_1001_0101;  tv_name[ 61] = "recall_p1_eta15_t17";
        tv_init[ 62] = 16'b1000_1011_1001_0101;  tv_expected[ 62] = 16'b0001_1011_1001_0101;  tv_name[ 62] = "recall_p1_eta15_t18";
        tv_init[ 63] = 16'b0001_0011_1001_0111;  tv_expected[ 63] = 16'b0001_1011_1001_0101;  tv_name[ 63] = "recall_p1_eta15_t19";
        tv_init[ 64] = 16'b1000_1011_1111_0001;  tv_expected[ 64] = 16'b0001_1011_1001_0101;  tv_name[ 64] = "recall_p1_eta30_t0";
        tv_init[ 65] = 16'b0111_1010_1011_0111;  tv_expected[ 65] = 16'b0001_1011_1001_0101;  tv_name[ 65] = "recall_p1_eta30_t1";
        tv_init[ 66] = 16'b0001_1001_0101_0000;  tv_expected[ 66] = 16'b0001_1011_1001_0101;  tv_name[ 66] = "recall_p1_eta30_t2";
        tv_init[ 67] = 16'b0000_1010_0010_0101;  tv_expected[ 67] = 16'b0001_1011_1001_0101;  tv_name[ 67] = "recall_p1_eta30_t3";
        tv_init[ 68] = 16'b0001_1000_0011_0111;  tv_expected[ 68] = 16'b0001_1011_1001_0101;  tv_name[ 68] = "recall_p1_eta30_t4";
        tv_init[ 69] = 16'b0000_1110_1011_0001;  tv_expected[ 69] = 16'b0001_1011_1001_0101;  tv_name[ 69] = "recall_p1_eta30_t5";
        tv_init[ 70] = 16'b1111_1011_1101_1101;  tv_expected[ 70] = 16'b0001_1011_1001_0101;  tv_name[ 70] = "recall_p1_eta30_t6";
        tv_init[ 71] = 16'b1001_1101_1001_1100;  tv_expected[ 71] = 16'b0001_1011_1001_0101;  tv_name[ 71] = "recall_p1_eta30_t7";
        tv_init[ 72] = 16'b0100_0001_1101_0101;  tv_expected[ 72] = 16'b0001_1011_1001_0101;  tv_name[ 72] = "recall_p1_eta30_t8";
        tv_init[ 73] = 16'b0111_0111_1001_0001;  tv_expected[ 73] = 16'b0001_1011_1001_0101;  tv_name[ 73] = "recall_p1_eta30_t9";
        tv_init[ 74] = 16'b0101_1101_0001_0001;  tv_expected[ 74] = 16'b0001_1011_1001_0101;  tv_name[ 74] = "recall_p1_eta30_t10";
        tv_init[ 75] = 16'b1101_1010_0001_0100;  tv_expected[ 75] = 16'b0001_1011_1001_0101;  tv_name[ 75] = "recall_p1_eta30_t11";
        tv_init[ 76] = 16'b0001_1011_1010_0010;  tv_expected[ 76] = 16'b0001_1011_1001_0101;  tv_name[ 76] = "recall_p1_eta30_t12";
        tv_init[ 77] = 16'b0111_1111_1011_1101;  tv_expected[ 77] = 16'b0001_1011_1001_0101;  tv_name[ 77] = "recall_p1_eta30_t13";
        tv_init[ 78] = 16'b0100_1111_1001_1001;  tv_expected[ 78] = 16'b0001_1011_1001_0101;  tv_name[ 78] = "recall_p1_eta30_t14";
        tv_init[ 79] = 16'b1101_1001_1000_0111;  tv_expected[ 79] = 16'b0001_1011_1001_0101;  tv_name[ 79] = "recall_p1_eta30_t15";
        tv_init[ 80] = 16'b1001_1101_1000_0100;  tv_expected[ 80] = 16'b0001_1011_1001_0101;  tv_name[ 80] = "recall_p1_eta30_t16";
        tv_init[ 81] = 16'b1011_1011_0001_1100;  tv_expected[ 81] = 16'b0001_1011_1001_0101;  tv_name[ 81] = "recall_p1_eta30_t17";
        tv_init[ 82] = 16'b0001_1011_0000_1000;  tv_expected[ 82] = 16'b0001_1011_1001_0101;  tv_name[ 82] = "recall_p1_eta30_t18";
        tv_init[ 83] = 16'b1001_1010_1011_0110;  tv_expected[ 83] = 16'b0001_1011_1001_0101;  tv_name[ 83] = "recall_p1_eta30_t19";
        tv_init[ 84] = 16'b1010_0110_1011_0011;  tv_expected[ 84] = 16'b1010_0110_1011_0110;  tv_name[ 84] = "recall_p2_eta15_t0";
        tv_init[ 85] = 16'b1010_0110_0111_0110;  tv_expected[ 85] = 16'b1010_0110_1011_0110;  tv_name[ 85] = "recall_p2_eta15_t1";
        tv_init[ 86] = 16'b1010_1110_1111_0110;  tv_expected[ 86] = 16'b1010_0110_1011_0110;  tv_name[ 86] = "recall_p2_eta15_t2";
        tv_init[ 87] = 16'b1010_0000_1011_0110;  tv_expected[ 87] = 16'b1010_0110_1011_0110;  tv_name[ 87] = "recall_p2_eta15_t3";
        tv_init[ 88] = 16'b1011_0110_1011_0100;  tv_expected[ 88] = 16'b1010_0110_1011_0110;  tv_name[ 88] = "recall_p2_eta15_t4";
        tv_init[ 89] = 16'b1000_0110_0011_0110;  tv_expected[ 89] = 16'b1010_0110_1011_0110;  tv_name[ 89] = "recall_p2_eta15_t5";
        tv_init[ 90] = 16'b1010_0011_1011_0110;  tv_expected[ 90] = 16'b1010_0110_1011_0110;  tv_name[ 90] = "recall_p2_eta15_t6";
        tv_init[ 91] = 16'b1011_0100_1011_0110;  tv_expected[ 91] = 16'b1010_0110_1011_0110;  tv_name[ 91] = "recall_p2_eta15_t7";
        tv_init[ 92] = 16'b1010_1110_1011_0100;  tv_expected[ 92] = 16'b1010_0110_1011_0110;  tv_name[ 92] = "recall_p2_eta15_t8";
        tv_init[ 93] = 16'b1010_0111_0011_0110;  tv_expected[ 93] = 16'b1010_0110_1011_0110;  tv_name[ 93] = "recall_p2_eta15_t9";
        tv_init[ 94] = 16'b1011_0110_1011_0010;  tv_expected[ 94] = 16'b1010_0110_1011_0110;  tv_name[ 94] = "recall_p2_eta15_t10";
        tv_init[ 95] = 16'b1010_0100_0011_0110;  tv_expected[ 95] = 16'b1010_0110_1011_0110;  tv_name[ 95] = "recall_p2_eta15_t11";
        tv_init[ 96] = 16'b1010_0110_0011_0100;  tv_expected[ 96] = 16'b1010_0110_1011_0110;  tv_name[ 96] = "recall_p2_eta15_t12";
        tv_init[ 97] = 16'b1010_0011_1011_0110;  tv_expected[ 97] = 16'b1010_0110_1011_0110;  tv_name[ 97] = "recall_p2_eta15_t13";
        tv_init[ 98] = 16'b1011_0110_1011_0111;  tv_expected[ 98] = 16'b1010_0110_1011_0110;  tv_name[ 98] = "recall_p2_eta15_t14";
        tv_init[ 99] = 16'b1001_0110_1011_0110;  tv_expected[ 99] = 16'b1010_0110_1011_0110;  tv_name[ 99] = "recall_p2_eta15_t15";
        tv_init[100] = 16'b1010_0110_1001_0100;  tv_expected[100] = 16'b1010_0110_1011_0110;  tv_name[100] = "recall_p2_eta15_t16";
        tv_init[101] = 16'b1011_0010_1011_0110;  tv_expected[101] = 16'b1010_0110_1011_0110;  tv_name[101] = "recall_p2_eta15_t17";
        tv_init[102] = 16'b1010_0100_1001_0110;  tv_expected[102] = 16'b1010_0110_1011_0110;  tv_name[102] = "recall_p2_eta15_t18";
        tv_init[103] = 16'b1010_0110_1000_0110;  tv_expected[103] = 16'b1010_0110_1011_0110;  tv_name[103] = "recall_p2_eta15_t19";
        tv_init[104] = 16'b0010_0100_0010_0010;  tv_expected[104] = 16'b1010_0110_1011_0110;  tv_name[104] = "recall_p2_eta30_t0";
        tv_init[105] = 16'b0110_0110_1111_1100;  tv_expected[105] = 16'b1010_0110_1011_0110;  tv_name[105] = "recall_p2_eta30_t1";
        tv_init[106] = 16'b1110_1010_1001_0100;  tv_expected[106] = 16'b1010_0110_1011_0110;  tv_name[106] = "recall_p2_eta30_t2";
        tv_init[107] = 16'b1010_0100_0011_0001;  tv_expected[107] = 16'b1010_0110_1011_0110;  tv_name[107] = "recall_p2_eta30_t3";
        tv_init[108] = 16'b1010_1010_1101_0100;  tv_expected[108] = 16'b1010_0110_1011_0110;  tv_name[108] = "recall_p2_eta30_t4";
        tv_init[109] = 16'b0000_1111_1001_0110;  tv_expected[109] = 16'b1010_0110_1011_0110;  tv_name[109] = "recall_p2_eta30_t5";
        tv_init[110] = 16'b0010_0110_1100_0100;  tv_expected[110] = 16'b1010_0110_1011_0110;  tv_name[110] = "recall_p2_eta30_t6";
        tv_init[111] = 16'b1110_0111_0111_0111;  tv_expected[111] = 16'b1010_0110_1011_0110;  tv_name[111] = "recall_p2_eta30_t7";
        tv_init[112] = 16'b0100_0111_1011_0100;  tv_expected[112] = 16'b1010_0110_1011_0110;  tv_name[112] = "recall_p2_eta30_t8";
        tv_init[113] = 16'b1001_0110_0001_0100;  tv_expected[113] = 16'b1010_0110_1011_0110;  tv_name[113] = "recall_p2_eta30_t9";
        tv_init[114] = 16'b1110_0010_1101_1110;  tv_expected[114] = 16'b1010_0110_1011_0110;  tv_name[114] = "recall_p2_eta30_t10";
        tv_init[115] = 16'b0010_0111_0011_0000;  tv_expected[115] = 16'b1010_0110_1011_0110;  tv_name[115] = "recall_p2_eta30_t11";
        tv_init[116] = 16'b0000_0111_1010_1110;  tv_expected[116] = 16'b1010_0110_1011_0110;  tv_name[116] = "recall_p2_eta30_t12";
        tv_init[117] = 16'b1011_1100_1011_1100;  tv_expected[117] = 16'b1010_0110_1011_0110;  tv_name[117] = "recall_p2_eta30_t13";
        tv_init[118] = 16'b1001_1110_1001_1110;  tv_expected[118] = 16'b1010_0110_1011_0110;  tv_name[118] = "recall_p2_eta30_t14";
        tv_init[119] = 16'b1110_1110_1001_0000;  tv_expected[119] = 16'b1010_0110_1011_0110;  tv_name[119] = "recall_p2_eta30_t15";
        tv_init[120] = 16'b1010_0110_0001_1011;  tv_expected[120] = 16'b1010_0110_1011_0110;  tv_name[120] = "recall_p2_eta30_t16";
        tv_init[121] = 16'b1000_1000_1011_0111;  tv_expected[121] = 16'b1010_0110_1011_0110;  tv_name[121] = "recall_p2_eta30_t17";
        tv_init[122] = 16'b1100_0110_0011_0000;  tv_expected[122] = 16'b1010_0110_1011_0110;  tv_name[122] = "recall_p2_eta30_t18";
        tv_init[123] = 16'b1101_0110_1001_0010;  tv_expected[123] = 16'b1010_0110_1011_0110;  tv_name[123] = "recall_p2_eta30_t19";
        tv_init[124] = 16'b1001_1101_0010_0111;  tv_expected[124] = 16'b1011_1101_0000_0111;  tv_name[124] = "recall_p3_eta15_t0";
        tv_init[125] = 16'b1011_0101_0000_0101;  tv_expected[125] = 16'b1011_1101_0000_0111;  tv_name[125] = "recall_p3_eta15_t1";
        tv_init[126] = 16'b1011_0101_0001_0111;  tv_expected[126] = 16'b1011_1101_0000_0111;  tv_name[126] = "recall_p3_eta15_t2";
        tv_init[127] = 16'b1111_1100_0000_0111;  tv_expected[127] = 16'b1011_1101_0000_0111;  tv_name[127] = "recall_p3_eta15_t3";
        tv_init[128] = 16'b1111_1101_0000_0011;  tv_expected[128] = 16'b1011_1101_0000_0111;  tv_name[128] = "recall_p3_eta15_t4";
        tv_init[129] = 16'b0011_1101_0000_0110;  tv_expected[129] = 16'b1011_1101_0000_0111;  tv_name[129] = "recall_p3_eta15_t5";
        tv_init[130] = 16'b1111_1101_0000_0101;  tv_expected[130] = 16'b1011_1101_0000_0111;  tv_name[130] = "recall_p3_eta15_t6";
        tv_init[131] = 16'b1011_1011_0000_0111;  tv_expected[131] = 16'b1011_1101_0000_0111;  tv_name[131] = "recall_p3_eta15_t7";
        tv_init[132] = 16'b1010_1001_0000_0111;  tv_expected[132] = 16'b1011_1101_0000_0111;  tv_name[132] = "recall_p3_eta15_t8";
        tv_init[133] = 16'b0011_1101_0010_0111;  tv_expected[133] = 16'b1011_1101_0000_0111;  tv_name[133] = "recall_p3_eta15_t9";
        tv_init[134] = 16'b0011_1101_1000_0111;  tv_expected[134] = 16'b1011_1101_0000_0111;  tv_name[134] = "recall_p3_eta15_t10";
        tv_init[135] = 16'b0011_0101_0000_0111;  tv_expected[135] = 16'b1011_1101_0000_0111;  tv_name[135] = "recall_p3_eta15_t11";
        tv_init[136] = 16'b1011_1101_0001_0101;  tv_expected[136] = 16'b1011_1101_0000_0111;  tv_name[136] = "recall_p3_eta15_t12";
        tv_init[137] = 16'b1001_1101_0000_0101;  tv_expected[137] = 16'b1011_1101_0000_0111;  tv_name[137] = "recall_p3_eta15_t13";
        tv_init[138] = 16'b0011_1101_0000_1111;  tv_expected[138] = 16'b1011_1101_0000_0111;  tv_name[138] = "recall_p3_eta15_t14";
        tv_init[139] = 16'b1011_1111_0001_0111;  tv_expected[139] = 16'b1011_1101_0000_0111;  tv_name[139] = "recall_p3_eta15_t15";
        tv_init[140] = 16'b1010_1101_1000_0111;  tv_expected[140] = 16'b1011_1101_0000_0111;  tv_name[140] = "recall_p3_eta15_t16";
        tv_init[141] = 16'b1011_1001_0000_0011;  tv_expected[141] = 16'b1011_1101_0000_0111;  tv_name[141] = "recall_p3_eta15_t17";
        tv_init[142] = 16'b0111_1101_0000_0111;  tv_expected[142] = 16'b1011_1101_0000_0111;  tv_name[142] = "recall_p3_eta15_t18";
        tv_init[143] = 16'b0011_1101_0100_0111;  tv_expected[143] = 16'b1011_1101_0000_0111;  tv_name[143] = "recall_p3_eta15_t19";
        tv_init[144] = 16'b1001_1101_0011_1101;  tv_expected[144] = 16'b1011_1101_0000_0111;  tv_name[144] = "recall_p3_eta30_t0";
        tv_init[145] = 16'b1001_1000_0000_0010;  tv_expected[145] = 16'b1011_1101_0000_0111;  tv_name[145] = "recall_p3_eta30_t1";
        tv_init[146] = 16'b1111_1000_0000_1110;  tv_expected[146] = 16'b1011_1101_0000_0111;  tv_name[146] = "recall_p3_eta30_t2";
        tv_init[147] = 16'b1001_0100_0000_1011;  tv_expected[147] = 16'b1011_1101_0000_0111;  tv_name[147] = "recall_p3_eta30_t3";
        tv_init[148] = 16'b1111_0100_0010_0110;  tv_expected[148] = 16'b1011_1101_0000_0111;  tv_name[148] = "recall_p3_eta30_t4";
        tv_init[149] = 16'b1000_1001_0000_1110;  tv_expected[149] = 16'b1011_1101_0000_0111;  tv_name[149] = "recall_p3_eta30_t5";
        tv_init[150] = 16'b1001_1101_0001_1001;  tv_expected[150] = 16'b1011_1101_0000_0111;  tv_name[150] = "recall_p3_eta30_t6";
        tv_init[151] = 16'b0001_0101_0000_1101;  tv_expected[151] = 16'b1011_1101_0000_0111;  tv_name[151] = "recall_p3_eta30_t7";
        tv_init[152] = 16'b1010_1001_1010_0011;  tv_expected[152] = 16'b1011_1101_0000_0111;  tv_name[152] = "recall_p3_eta30_t8";
        tv_init[153] = 16'b1001_1011_0000_1011;  tv_expected[153] = 16'b1011_1101_0000_0111;  tv_name[153] = "recall_p3_eta30_t9";
        tv_init[154] = 16'b1000_1111_1000_0110;  tv_expected[154] = 16'b1011_1101_0000_0111;  tv_name[154] = "recall_p3_eta30_t10";
        tv_init[155] = 16'b1010_1101_0110_1110;  tv_expected[155] = 16'b1011_1101_0000_0111;  tv_name[155] = "recall_p3_eta30_t11";
        tv_init[156] = 16'b1111_1001_0010_1110;  tv_expected[156] = 16'b1011_1101_0000_0111;  tv_name[156] = "recall_p3_eta30_t12";
        tv_init[157] = 16'b1000_0101_1001_0111;  tv_expected[157] = 16'b1011_1101_0000_0111;  tv_name[157] = "recall_p3_eta30_t13";
        tv_init[158] = 16'b1011_1000_0001_1110;  tv_expected[158] = 16'b1011_1101_0000_0111;  tv_name[158] = "recall_p3_eta30_t14";
        tv_init[159] = 16'b0111_1101_0110_1111;  tv_expected[159] = 16'b1011_1101_0000_0111;  tv_name[159] = "recall_p3_eta30_t15";
        tv_init[160] = 16'b1111_0101_1000_1110;  tv_expected[160] = 16'b1011_1101_0000_0111;  tv_name[160] = "recall_p3_eta30_t16";
        tv_init[161] = 16'b1111_1001_1000_1101;  tv_expected[161] = 16'b1011_1101_0000_0111;  tv_name[161] = "recall_p3_eta30_t17";
        tv_init[162] = 16'b1111_1110_0000_0100;  tv_expected[162] = 16'b1011_1101_0000_0111;  tv_name[162] = "recall_p3_eta30_t18";
        tv_init[163] = 16'b1011_0100_0011_1111;  tv_expected[163] = 16'b1011_1101_0000_0111;  tv_name[163] = "recall_p3_eta30_t19";

        // ── Run all tests ─────────────────────────────────
        $display("");
        $display("=== Hopfield SV testbench: pseudoinverse_N16_M4_seed42 (N=16, M=4) ===");
        $display("");

        $display("--- Fixed-point tests (%0d patterns) ---", M);
        for (int t = 0; t < M; t++)
            run_one_test(t);

        $display("");
        $display("--- Noisy recall tests (%0d vectors) ---", N_TESTS - M);
        for (int t = M; t < N_TESTS; t++)
            run_one_test(t);

        // ── Summary ───────────────────────────────────────
        $display("");
        $display("=== SUMMARY: %0d / %0d passed  (%0d timeouts) ===",
                 pass_cnt, N_TESTS, timeout_cnt);
        if (fail_cnt == 0)
            $display("ALL TESTS PASSED");
        else
            $display("%0d FAILURES", fail_cnt);
        $display("");
        $finish;
    end

endmodule  // hopfield_tb
