#!/usr/bin/env python3
"""
Generate clockless HNN settling modules in SystemVerilog.

Three delay modes:
  depth     -- per-neuron delay from LUT term count depth
  even_odd  -- bipartite T_EVEN / T_ODD delays
  noise     -- depth + epsilon (seed-controlled)
"""

import math, json, os, random, argparse

# Default term counts from phase2/pla_min/pseudo_maxprune/ (N=16 max-prune network)
DEFAULT_TERMS = [3, 3, 13, 13, 7, 3, 13, 126, 3, 7, 3, 19, 19, 3, 386, 3]


def compute_depth(n_terms: int) -> int:
    if n_terms <= 0:
        return 1
    return 1 + math.ceil(math.log2(n_terms + 1))


def compute_depths(term_counts):
    return [compute_depth(t) for t in term_counts]


def _header(module_name: str, N: int) -> str:
    return f"""\
// Auto-generated by gen_clockless_sv.py
`timescale 1ns/1ps
module {module_name} #(
    parameter int N = {N}
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire            stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    hopfield_lut #(.N(N)) lut (.s(s), .s_next(s_next));
    // X-safe stable: ignore any X bits
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    // init_en override: immediately load init_val into s_settle
    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end
"""


def gen_depth_sv(N=16, term_counts=None) -> tuple:
    """Returns (sv_text, max_depth, depths_list)."""
    if term_counts is None:
        term_counts = DEFAULT_TERMS[:N]
    depths = compute_depths(term_counts)
    max_d = max(depths)

    lines = [_header("hopfield_clockless_depth", N)]
    lines.append("    // depth mode: delay = 1 + ceil(log2(n_terms+1))")
    lines.append("    always @(s_next or init_en or init_val) begin")
    lines.append("        if (init_en) begin")
    lines.append("            s_settle <= #0 init_val;")
    lines.append("        end else begin")
    for i, (d, t) in enumerate(zip(depths, term_counts)):
        lines.append(f"            s_settle[{i:3d}] <= #({d:3d}) s_next[{i:3d}];  // {t:4d} terms → depth {d}")
    lines.append("        end")
    lines.append("    end")
    lines.append("endmodule")
    return "\n".join(lines), max_d, depths


def gen_even_odd_sv(N=16, t_even=10, t_odd=24) -> tuple:
    """Returns (sv_text, max_depth)."""
    max_d = max(t_even, t_odd)

    lines = [_header("hopfield_clockless_even_odd", N)]
    lines.append(f"    // even_odd mode: T_EVEN={t_even}, T_ODD={t_odd}")
    lines.append(f"    localparam int T_EVEN = {t_even};")
    lines.append(f"    localparam int T_ODD  = {t_odd};")
    lines.append("    always @(s_next or init_en or init_val) begin")
    lines.append("        if (init_en) begin")
    lines.append("            s_settle <= #0 init_val;")
    lines.append("        end else begin")
    for i in range(N):
        tag = "T_EVEN" if i % 2 == 0 else "T_ODD"
        parity = "even" if i % 2 == 0 else "odd"
        lines.append(f"            s_settle[{i:3d}] <= #({tag}) s_next[{i:3d}];  // {parity}")
    lines.append("        end")
    lines.append("    end")
    lines.append("endmodule")
    return "\n".join(lines), max_d


def gen_noise_sv(N=16, term_counts=None, seed=99, noise_scale=0.5) -> tuple:
    """Returns (sv_text, max_depth, noisy_delays_list)."""
    if term_counts is None:
        term_counts = DEFAULT_TERMS[:N]
    depths = compute_depths(term_counts)

    rng = random.Random(seed)
    noisy = [max(1, round(d + rng.uniform(-noise_scale, noise_scale))) for d in depths]
    max_d = max(noisy)

    lines = [_header("hopfield_clockless_noise", N)]
    lines.append(f"    // noise mode: seed={seed}, scale={noise_scale}")
    lines.append("    always @(s_next or init_en or init_val) begin")
    lines.append("        if (init_en) begin")
    lines.append("            s_settle <= #0 init_val;")
    lines.append("        end else begin")
    for i, (nd, d) in enumerate(zip(noisy, depths)):
        lines.append(f"            s_settle[{i:3d}] <= #({nd:3d}) s_next[{i:3d}];  // base={d} noisy={nd}")
    lines.append("        end")
    lines.append("    end")
    lines.append("endmodule")
    return "\n".join(lines), max_d, noisy


def write_metadata(path, N, depths, terms, t_even=None, t_odd=None,
                   noise_seed=None, noise_delays=None):
    max_d = max(depths)
    meta = {
        "N": N,
        "depths": {str(i): d for i, d in enumerate(depths)},
        "terms": {str(i): t for i, t in enumerate(terms)},
        "max_depth": max_d,
        "settle_timeout": 64 * max_d,
    }
    if t_even is not None:
        meta["t_even"] = t_even
        meta["t_odd"] = t_odd
    if noise_seed is not None:
        meta["noise_seed"] = noise_seed
        meta["noise_delays"] = noise_delays
    with open(path, "w") as f:
        json.dump(meta, f, indent=2)
    return meta


def pla_term_counts(pla_dir, N):
    counts = []
    for i in range(N):
        pla_path = os.path.join(pla_dir, f"neuron_{i:03d}.pla")
        if not os.path.exists(pla_path):
            counts.append(1)
            continue
        n = 0
        with open(pla_path) as f:
            for line in f:
                line = line.strip()
                if line and line[0] in "01-":
                    n += 1
        counts.append(max(1, n))
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pla-dir", default="phase2/pla_min/pseudo_maxprune")
    ap.add_argument("--out-dir", default="phase2/rtl")
    ap.add_argument("--N", type=int, default=16)
    ap.add_argument("--modes", nargs="+", default=["depth", "even_odd", "noise"])
    ap.add_argument("--t-even", type=int, default=10)
    ap.add_argument("--t-odd", type=int, default=24)
    ap.add_argument("--noise-seed", type=int, default=99)
    ap.add_argument("--noise-scale", type=float, default=0.5)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    terms = pla_term_counts(args.pla_dir, args.N)
    print(f"Term counts: {terms}")

    depths = compute_depths(terms)
    print(f"Depths:      {depths}  (max={max(depths)})")

    if "depth" in args.modes:
        sv, max_d, d = gen_depth_sv(args.N, terms)
        path = os.path.join(args.out_dir, "clockless_depth.sv")
        with open(path, "w") as f:
            f.write(sv)
        write_metadata(
            os.path.join(args.out_dir, "clockless_depths.json"),
            args.N, d, terms
        )
        print(f"Wrote {path}  (max_depth={max_d})")

    if "even_odd" in args.modes:
        sv, max_d = gen_even_odd_sv(args.N, args.t_even, args.t_odd)
        path = os.path.join(args.out_dir, "clockless_even_odd.sv")
        with open(path, "w") as f:
            f.write(sv)
        print(f"Wrote {path}  (T_EVEN={args.t_even}, T_ODD={args.t_odd}, max_depth={max_d})")

    if "noise" in args.modes:
        sv, max_d, nd = gen_noise_sv(args.N, terms, args.noise_seed, args.noise_scale)
        path = os.path.join(args.out_dir, "clockless_noise.sv")
        with open(path, "w") as f:
            f.write(sv)
        print(f"Wrote {path}  (seed={args.noise_seed}, max_depth={max_d})")


if __name__ == "__main__":
    main()
