#!/usr/bin/env python3
"""
Build an asynchronous settling schedule for an arbitrary Hopfield network.

Given the network's coupling structure -- either a weight matrix W or explicit
per-neuron support sets -- this derives per-neuron NBA delays such that no two
interacting neurons ever latch at the same simulation time.

Method
  1. Coupling graph G: vertices = neurons, edge i--j iff neuron i reads neuron j
     (W[i][j] != 0) or vice versa.
  2. Proper vertex colouring of G (DSATUR). Two neurons may share a delay class
     only if they are NOT coupled, so a class never updates a pair that
     interacts -- that pair can never perform a synchronous joint update.
  3. Assign each class a delay from a pairwise-incommensurate pool (primes), so
     no two classes lock into a fixed phase relationship and re-synchronise.

The colouring number chi(G) is the minimum number of distinct delays needed.
Prefer the MINIMUM colouring: round-6 evidence shows over-separating (colouring
the graph square, or giving every neuron its own delay) settles strictly worse.

CLI:
    python3 schedule_hnn.py --npy W.npy --out sched.sv
"""

import argparse, json, math, os

# Pairwise-incommensurate delay pool. Any two distinct primes have a
# non-integer ratio, so no class pair re-aligns on a short period.
PRIMES = [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
          73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139]


# ─── coupling graph ──────────────────────────────────────────────────────────

def graph_from_W(W, tol=0.0):
    """Edges from a weight matrix. |W[i][j]| > tol means i reads j."""
    n = len(W)
    edges = set()
    for i in range(n):
        for j in range(n):
            if i != j and abs(W[i][j]) > tol:
                edges.add((min(i, j), max(i, j)))
    return n, sorted(edges)


def graph_from_supports(supports):
    """Edges from {neuron: set(inputs it reads)}."""
    n = len(supports)
    edges = set()
    for i, sup in supports.items():
        for j in sup:
            if i != j:
                edges.add((min(i, j), max(i, j)))
    return n, sorted(edges)


def adjacency(n, edges):
    adj = {i: set() for i in range(n)}
    for i, j in edges:
        adj[i].add(j)
        adj[j].add(i)
    return adj


# ─── colouring ───────────────────────────────────────────────────────────────

def dsatur(n, edges):
    """DSATUR colouring -- picks the vertex with the most distinctly-coloured
    neighbours next. Beats degree-ordered greedy on most graphs and matches it
    in the worst case, so it needs fewer delay classes."""
    adj = adjacency(n, edges)
    colour, sat = {}, {i: set() for i in range(n)}
    for _ in range(n):
        # highest saturation, break ties on highest remaining degree
        v = max((i for i in range(n) if i not in colour),
                key=lambda i: (len(sat[i]), len(adj[i])))
        c = 0
        while c in sat[v]:
            c += 1
        colour[v] = c
        for u in adj[v]:
            sat[u].add(c)
    return colour


def verify(colour, edges):
    """Coupled pairs sharing a class. Must be empty for a valid schedule."""
    return [(i, j) for (i, j) in edges if colour[i] == colour[j]]


def incommensurate(delays):
    """True if no delay divides another -- no pair re-aligns on a short period."""
    for a in delays:
        for b in delays:
            if a != b and max(a, b) % min(a, b) == 0:
                return False
    return True


# ─── schedule ────────────────────────────────────────────────────────────────

def build_schedule(n, edges, delay_pool=None):
    """Returns (colour_map, per_neuron_delays, info)."""
    colour = dsatur(n, edges)
    k = max(colour.values()) + 1
    pool = list(delay_pool or PRIMES)
    if k > len(pool):
        raise ValueError(f"need {k} delay classes, pool has {len(pool)}")
    class_delays = pool[:k]
    delays = [class_delays[colour[i]] for i in range(n)]

    bad = verify(colour, edges)
    info = {
        "n_neurons": n,
        "n_edges": len(edges),
        "density": len(edges) / (n * (n - 1) / 2) if n > 1 else 0.0,
        "n_classes": k,
        "class_delays": class_delays,
        "conflicts": bad,
        "valid_colouring": not bad,
        "incommensurate": incommensurate(class_delays),
        "max_delay": max(delays),
        "suggested_timeout": 64 * max(delays) + 100,
        "classes": {str(i): colour[i] for i in range(n)},
    }
    return colour, delays, info


def emit_sv(n, delays, colour, module_name="hopfield_clockless_sched",
            lut_module="hopfield_lut"):
    L = [f"""\
// Auto-generated by schedule_hnn.py -- graph-coloured async schedule
`timescale 1ns/1ps
module {module_name} #(
    parameter int N = {n}
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire           stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    {lut_module} #(.N(N)) lut (.s(s), .s_next(s_next));
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end

    always @(s_next or init_en or init_val) begin
        if (init_en) begin
            s_settle <= #0 init_val;
        end else begin"""]
    for i in range(n):
        L.append(f"            s_settle[{i:3d}] <= #({delays[i]:3d}) s_next[{i:3d}];"
                 f"  // class {colour[i]}")
    L += ["        end", "    end", "endmodule"]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npy", help="path to a .npy weight matrix")
    ap.add_argument("--tol", type=float, default=0.0,
                    help="|W[i][j]| > tol counts as a coupling")
    ap.add_argument("--out", help="write SystemVerilog here")
    ap.add_argument("--json", help="write schedule metadata here")
    ap.add_argument("--module", default="hopfield_clockless_sched")
    args = ap.parse_args()

    if not args.npy:
        ap.error("--npy is required")
    import numpy as np
    W = np.load(args.npy)
    n, edges = graph_from_W(W, args.tol)
    colour, delays, info = build_schedule(n, edges)

    print(f"neurons={info['n_neurons']} edges={info['n_edges']} "
          f"density={info['density']:.3f}")
    print(f"classes={info['n_classes']} delays={info['class_delays']}")
    print(f"valid_colouring={info['valid_colouring']} "
          f"incommensurate={info['incommensurate']}")
    print(f"max_delay={info['max_delay']} "
          f"suggested_timeout={info['suggested_timeout']}ns")
    if info["conflicts"]:
        print(f"WARNING: {len(info['conflicts'])} coupled pairs share a class")

    if args.out:
        with open(args.out, "w") as f:
            f.write(emit_sv(n, delays, colour, args.module))
        print(f"wrote {args.out}")
    if args.json:
        with open(args.json, "w") as f:
            json.dump(info, f, indent=2)
        print(f"wrote {args.json}")


if __name__ == "__main__":
    main()
