// Auto-generated by gen_clockless_sv.py
`timescale 1ns/1ps
module hopfield_clockless_coloring #(
    parameter int N = 16
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire            stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    hopfield_lut #(.N(N)) lut (.s(s), .s_next(s_next));
    // X-safe stable: ignore any X bits
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    // init_en override: immediately load init_val into s_settle
    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end

    // coloring mode: 16 classes, delays=[11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]
    // scheme=distinct
    always @(s_next or init_en or init_val) begin
        if (init_en) begin
            s_settle <= #0 init_val;
        end else begin
            s_settle[  0] <= #( 11) s_next[  0];  // class 0
            s_settle[  1] <= #( 13) s_next[  1];  // class 1
            s_settle[  2] <= #( 17) s_next[  2];  // class 2
            s_settle[  3] <= #( 19) s_next[  3];  // class 3
            s_settle[  4] <= #( 23) s_next[  4];  // class 4
            s_settle[  5] <= #( 29) s_next[  5];  // class 5
            s_settle[  6] <= #( 31) s_next[  6];  // class 6
            s_settle[  7] <= #( 37) s_next[  7];  // class 7
            s_settle[  8] <= #( 41) s_next[  8];  // class 8
            s_settle[  9] <= #( 43) s_next[  9];  // class 9
            s_settle[ 10] <= #( 47) s_next[ 10];  // class 10
            s_settle[ 11] <= #( 53) s_next[ 11];  // class 11
            s_settle[ 12] <= #( 59) s_next[ 12];  // class 12
            s_settle[ 13] <= #( 61) s_next[ 13];  // class 13
            s_settle[ 14] <= #( 67) s_next[ 14];  // class 14
            s_settle[ 15] <= #( 71) s_next[ 15];  // class 15
        end
    end
endmodule