// Auto-generated by gen_clockless_sv.py
`timescale 1ns/1ps
module hopfield_clockless_depth #(
    parameter int N = 16
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire            stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    hopfield_lut #(.N(N)) lut (.s(s), .s_next(s_next));
    // X-safe stable: ignore any X bits
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    // init_en override: immediately load init_val into s_settle
    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end

    // depth mode: delay = 1 + ceil(log2(n_terms+1))
    always @(s_next or init_en or init_val) begin
        if (init_en) begin
            s_settle <= #0 init_val;
        end else begin
            s_settle[  0] <= #(  3) s_next[  0];  //    3 terms → depth 3
            s_settle[  1] <= #(  3) s_next[  1];  //    3 terms → depth 3
            s_settle[  2] <= #(  5) s_next[  2];  //   13 terms → depth 5
            s_settle[  3] <= #(  5) s_next[  3];  //   13 terms → depth 5
            s_settle[  4] <= #(  4) s_next[  4];  //    7 terms → depth 4
            s_settle[  5] <= #(  3) s_next[  5];  //    3 terms → depth 3
            s_settle[  6] <= #(  5) s_next[  6];  //   13 terms → depth 5
            s_settle[  7] <= #(  8) s_next[  7];  //  126 terms → depth 8
            s_settle[  8] <= #(  3) s_next[  8];  //    3 terms → depth 3
            s_settle[  9] <= #(  4) s_next[  9];  //    7 terms → depth 4
            s_settle[ 10] <= #(  3) s_next[ 10];  //    3 terms → depth 3
            s_settle[ 11] <= #(  6) s_next[ 11];  //   19 terms → depth 6
            s_settle[ 12] <= #(  6) s_next[ 12];  //   19 terms → depth 6
            s_settle[ 13] <= #(  3) s_next[ 13];  //    3 terms → depth 3
            s_settle[ 14] <= #( 10) s_next[ 14];  //  386 terms → depth 10
            s_settle[ 15] <= #(  3) s_next[ 15];  //    3 terms → depth 3
        end
    end
endmodule