// Auto-generated by gen_clockless_sv.py
`timescale 1ns/1ps
module hopfield_clockless_even_odd #(
    parameter int N = 16
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire            stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    hopfield_lut #(.N(N)) lut (.s(s), .s_next(s_next));
    // X-safe stable: ignore any X bits
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    // init_en override: immediately load init_val into s_settle
    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end

    // even_odd mode: T_EVEN=10, T_ODD=24
    localparam int T_EVEN = 10;
    localparam int T_ODD  = 24;
    always @(s_next or init_en or init_val) begin
        if (init_en) begin
            s_settle <= #0 init_val;
        end else begin
            s_settle[  0] <= #(T_EVEN) s_next[  0];  // even
            s_settle[  1] <= #(T_ODD) s_next[  1];  // odd
            s_settle[  2] <= #(T_EVEN) s_next[  2];  // even
            s_settle[  3] <= #(T_ODD) s_next[  3];  // odd
            s_settle[  4] <= #(T_EVEN) s_next[  4];  // even
            s_settle[  5] <= #(T_ODD) s_next[  5];  // odd
            s_settle[  6] <= #(T_EVEN) s_next[  6];  // even
            s_settle[  7] <= #(T_ODD) s_next[  7];  // odd
            s_settle[  8] <= #(T_EVEN) s_next[  8];  // even
            s_settle[  9] <= #(T_ODD) s_next[  9];  // odd
            s_settle[ 10] <= #(T_EVEN) s_next[ 10];  // even
            s_settle[ 11] <= #(T_ODD) s_next[ 11];  // odd
            s_settle[ 12] <= #(T_EVEN) s_next[ 12];  // even
            s_settle[ 13] <= #(T_ODD) s_next[ 13];  // odd
            s_settle[ 14] <= #(T_EVEN) s_next[ 14];  // even
            s_settle[ 15] <= #(T_ODD) s_next[ 15];  // odd
        end
    end
endmodule