// Auto-generated by gen_clockless_sv.py
`timescale 1ns/1ps
module hopfield_clockless_noise #(
    parameter int N = 16
) (
    input  wire           init_en,
    input  wire  [N-1:0]  init_val,
    output wire  [N-1:0]  s,
    output wire  [N-1:0]  s_next,
    output wire            stable
);
    logic [N-1:0] s_settle;
    initial s_settle = '0;
    assign s = init_en ? init_val : s_settle;
    hopfield_lut #(.N(N)) lut (.s(s), .s_next(s_next));
    // X-safe stable: ignore any X bits
    assign stable = (&(s|~s)) & (&(s_next|~s_next)) & (s === s_next);

    // init_en override: immediately load init_val into s_settle
    always @(init_en or init_val) begin
        if (init_en) s_settle <= #0 init_val;
    end

    // noise mode: seed=99, scale=0.5
    always @(s_next or init_en or init_val) begin
        if (init_en) begin
            s_settle <= #0 init_val;
        end else begin
            s_settle[  0] <= #(  3) s_next[  0];  // base=3 noisy=3
            s_settle[  1] <= #(  3) s_next[  1];  // base=3 noisy=3
            s_settle[  2] <= #(  5) s_next[  2];  // base=5 noisy=5
            s_settle[  3] <= #(  5) s_next[  3];  // base=5 noisy=5
            s_settle[  4] <= #(  4) s_next[  4];  // base=4 noisy=4
            s_settle[  5] <= #(  3) s_next[  5];  // base=3 noisy=3
            s_settle[  6] <= #(  5) s_next[  6];  // base=5 noisy=5
            s_settle[  7] <= #(  8) s_next[  7];  // base=8 noisy=8
            s_settle[  8] <= #(  3) s_next[  8];  // base=3 noisy=3
            s_settle[  9] <= #(  4) s_next[  9];  // base=4 noisy=4
            s_settle[ 10] <= #(  3) s_next[ 10];  // base=3 noisy=3
            s_settle[ 11] <= #(  6) s_next[ 11];  // base=6 noisy=6
            s_settle[ 12] <= #(  6) s_next[ 12];  // base=6 noisy=6
            s_settle[ 13] <= #(  3) s_next[ 13];  // base=3 noisy=3
            s_settle[ 14] <= #( 10) s_next[ 14];  // base=10 noisy=10
            s_settle[ 15] <= #(  3) s_next[ 15];  // base=3 noisy=3
        end
    end
endmodule