"""
sv_export.py
============
Emit synthesizable, hazard-free **SystemVerilog** from the minimized
Boolean covers produced by logic_minimize.py.

What is generated
-----------------
For a network of N neurons the script produces a single file:

    neuron_logic_generated.sv

containing one module per neuron:

    module neuron_update_i #(parameter N = <N>) (
        input  logic [N-1:0] b_in,   // current state (binary, 0↔-1, 1↔+1)
        output logic          b_out  // next state of neuron i
    );
        // Hazard-free SOP cover
        assign b_out = (term_0) | (term_1) | ...;
    endmodule

and a wrapper module:

    module neuron_logic_bank #(parameter N = <N>) (
        input  logic [N-1:0] b_in,
        output logic [N-1:0] b_out
    );
        // instantiates neuron_update_0 … neuron_update_{N-1}
    endmodule

Hazard strategy
---------------
All logic uses registered (synchronous) outputs in the RTL top level, so
combinational glitches are masked at clock edges.  Additionally, the covers
themselves are hazard-free by construction (see logic_minimize.py), so even
if this combinational block is used asynchronously the output is glitch-free.

Usage
-----
    python sv_export.py --tt-json tt/truth_tables.json \\
                        --out rtl/neuron_logic_generated.sv
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from logic_minimize import Cover, minimize_all, cover_to_sv_expr
from truth_table_gen import NeuronTruthTable, load_json


# ---------------------------------------------------------------------------
# Template helpers
# ---------------------------------------------------------------------------

_FILE_HEADER = """\
// =============================================================================
// neuron_logic_generated.sv
// AUTO-GENERATED by sv_export.py — DO NOT EDIT BY HAND
// Generated : {timestamp}
// N neurons : {N}
// Hazard-free SOP cover for each neuron's synchronous update function:
//   b_i_new = sign( sum_j W_ij * (2*b_j - 1) )
//           = 1  if  net input >= 0
//             0  otherwise
// Bipolar ↔ binary:  state +1 → bit 1,  state -1 → bit 0
// =============================================================================

`timescale 1ns/1ps
"""

_NEURON_MODULE = """\
// ----------------------------------------------------------------------------
// Neuron {i} update logic  ({n_terms} product terms)
// ----------------------------------------------------------------------------
module neuron_update_{i}
#(
    parameter int N = {N}
)
(
    input  logic [N-1:0] b_in,   // current state word
    output logic          b_out  // next state of this neuron
);
    // SOP expression (hazard-free cover)
    // Variables: b_in[N-1] is neuron 0 (MSB), b_in[0] is neuron N-1 (LSB)
    assign b_out = {sv_expr};

endmodule

"""

_BANK_MODULE_HEADER = """\
// ----------------------------------------------------------------------------
// Neuron-logic bank: instantiates all N per-neuron update modules
// ----------------------------------------------------------------------------
module neuron_logic_bank
#(
    parameter int N = {N}
)
(
    input  logic [N-1:0] b_in,   // current state
    output logic [N-1:0] b_out   // next state (combinational)
);

"""

_BANK_INST = """\
    neuron_update_{i} #(.N(N)) u_neuron_{i} (
        .b_in  (b_in),
        .b_out (b_out[{bit}])
    );
"""

_BANK_MODULE_FOOTER = """\
endmodule
"""


# ---------------------------------------------------------------------------
# Core generator
# ---------------------------------------------------------------------------

def generate_sv(
    tables: List[NeuronTruthTable],
    covers: List[Cover],
    out_path: Path,
    module_prefix: str = "neuron_update",
) -> None:
    """
    Write a SystemVerilog file containing per-neuron combinational modules
    and a bank wrapper.

    Parameters
    ----------
    tables       : truth tables (for metadata / comments)
    covers       : minimized Boolean covers, one per neuron
    out_path     : destination .sv file
    module_prefix: prefix for individual neuron module names
    """
    N = tables[0].N
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []

    # File header
    lines.append(
        _FILE_HEADER.format(
            timestamp=datetime.now().isoformat(timespec="seconds"),
            N=N,
        )
    )

    # Per-neuron modules
    for i, (tt, cover) in enumerate(zip(tables, covers)):
        # Variable names: b_in[N-1] = neuron 0, b_in[0] = neuron N-1
        var_names = [f"b_in[{N-1-j}]" for j in range(N)]
        sv_expr = cover_to_sv_expr(cover, var_names)

        on_count  = len(tt.on_set)
        off_count = (1 << N) - on_count

        # Add a comment with ON-set fraction
        lines.append(
            f"// Neuron {i}: on_set={on_count}/{1<<N} "
            f"({100*on_count/(1<<N):.1f}%)  "
            f"off_set={off_count}/{1<<N}\n"
        )
        lines.append(
            _NEURON_MODULE.format(
                i=i,
                N=N,
                n_terms=len(cover),
                sv_expr=sv_expr,
            )
        )

    # Bank wrapper
    lines.append(_BANK_MODULE_HEADER.format(N=N))
    for i in range(N):
        # neuron 0 drives the MSB (b_out[N-1]), neuron N-1 drives b_out[0]
        lines.append(_BANK_INST.format(i=i, bit=N - 1 - i))
    lines.append(_BANK_MODULE_FOOTER)

    with open(out_path, "w") as f:
        f.writelines(lines)

    print(f"SystemVerilog written to {out_path}  ({N} neurons, {N} modules)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Emit hazard-free SystemVerilog from minimized truth tables."
    )
    parser.add_argument(
        "--tt-json", type=str, required=True,
        help="JSON file from truth_table_gen.py"
    )
    parser.add_argument(
        "--out", type=str, default="rtl/neuron_logic_generated.sv",
        help="Output .sv file path"
    )
    parser.add_argument(
        "--no-hazard-free", action="store_true",
        help="Skip hazard-free augmentation"
    )
    args = parser.parse_args()

    tables = load_json(args.tt_json)
    covers = minimize_all(tables, hazard_free=not args.no_hazard_free)
    generate_sv(tables, covers, Path(args.out))
